version: '3'
services:
  web:
    container_name: web
    image: rails
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./project:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    restart: always
