version: '3'
services:
  web:
    container_name: web
    image: rails
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./project:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    container_name: db
    image: mysql:8.0.31-oracle
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume:
