inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Documentation:
  Enabled: false
MethodLength:
  CountComments: false
  Max: 50
Metrics/AbcSize:
  Max: 50

RSpec/ContextWording:
  Enabled: false
